spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s


# configure tomcat server
server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s